Add uniffi
lambdaclass/lambdaworks pull request #176
Opened 2023-03-13 20:36 UTC by mfachal

# Add Uniffi for python bindings

## Description

Adds uniffi for python bindings for stark lib.

## Type of change

Please delete options that are not relevant.

- New feature

## Checklist
- [ ] Linked to Github Issue
- [ ] Unit tests added
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] This change is an Optimization
  - [ ] Benchmarks added/run

2023-03-14 15:29 UTC, jpcenteno requested changes

2023-03-14 15:29 UTC, jpcenteno commented on Makefile
> +	cargo run --release --bin lambdaworks-stark generate proving-system/stark/src/lambdaworks_stark.udl --language python --out-dir target/python/ --no-format
Remember that we have to copy the dylib into `target/python` for it to work

2023-03-14 15:29 UTC, jpcenteno commented on proving-system/stark/src/lib.rs
> +type Result<T, E = ArithmeticError> = std::result::Result<T, E>;
This is great for testing, but we shouldn't merge this.

Let's discuss how to do this.

2023-03-14 15:29 UTC, jpcenteno commented on proving-system/stark/Cargo.toml
> +path = "lambdaworks_stark.rs"
I would rename this to "lambdaworks-stark-uniffi"

2023-03-14 16:33 UTC, jpcenteno commented
Python tests are running on the CI https://github.com/lambdaclass/lambdaworks/actions/runs/4409823169/jobs/7726590088#step:5:639

2023-08-31 14:39 UTC, MauroToscano commented
This hasn't been active for a while. Closing it.

2023-08-31 14:39 UTC, closed without merging