Add feature flag to "disable" Fiat-Shamir
lambdaclass/lambdaworks pull request #242
Opened 2023-04-10 21:22 UTC by jrchatruc

## Description

This PR adds a feature flag `dummy_fiat_shamir` that effectively disables Fiat-Shamir when running the stark prover and verifier. This means that if you run something like

```
cargo test test_prove_fib --features dummy_fiat_shamir
```

the fibonacci tests will run with a transcript that always returns the same value. This is useful for debugging.

To do this, `Transcript` was turned into a `Trait` and a `DefaultTranscript` and `TestTranscript` structs were introduced.

## Type of change

Please delete options that are not relevant.

- [x] New feature

2023-04-11 09:52 UTC, MauroToscano commented
In the future if we add more debug tools like this we could add one feature to enable them all, for simplicity

2023-04-11 09:52 UTC, MauroToscano requested changes

2023-04-11 13:22 UTC, MauroToscano approved these changes

2023-04-12 21:27 UTC, entropidelic approved these changes

2023-04-12 21:27 UTC, merged