feat: add cairo trace
lambdaclass/lambdaworks pull request #251
Opened 2023-04-12 21:54 UTC by entropidelic

# TITLE

## Description

Description of the pull request changes and motivation.

## Type of change

Please delete options that are not relevant.

- [ ] New feature
- [ ] Bug fix
- [ ] Optimization

## Checklist
- [ ] Linked to Github Issue
- [ ] Unit tests added
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] This change is an Optimization
  - [ ] Benchmarks added/run

2023-04-20 18:19 UTC, ilitteri approved these changes
LGTM as it is. Left some comments, questions & suggestions

2023-04-20 18:19 UTC, ilitteri commented on proving_system/stark/src/air/trace.rs
> +        // dbg!(&n_rows);
Should we remove this?

2023-04-20 18:19 UTC, ilitteri commented on proving_system/stark/src/cairo_vm/execution_trace.rs
> +        flags.iter().map(|f| f.to_trace_representation()).collect();
```suggestion
        flags.iter().map(CairoInstructionFlags::to_trace_representation).collect();
```

2023-04-20 18:19 UTC, ilitteri commented on proving_system/stark/src/cairo_vm/execution_trace.rs
> +        .map(|off| off.to_trace_representation())
```suggestion
        .map(InstructionOffsets::to_trace_representation)
```

2023-04-20 18:19 UTC, ilitteri commented on proving_system/stark/src/cairo_vm/execution_trace.rs
> +fn compute_res(flags: &[CairoInstructionFlags], op0s: &[FE], op1s: &[FE]) -> Vec<FE> {
We could file an issue for removing the `panic`s of this function.

2023-04-20 18:19 UTC, ilitteri commented on proving_system/stark/src/cairo_vm/instruction_flags.rs
> +pub(crate) fn aux_get_last_nim_of_FE(value: &FE) -> u64 {
We could get rid of this annotation renaming the function with something like this:
```suggestion
#[allow(non_snake_case)]
pub(crate) fn aux_get_last_nim_of_field_element(value: &FE) -> u64 {
```
or
```suggestion
#[allow(non_snake_case)]
pub(crate) fn aux_get_last_nim_of_felt(value: &FE) -> u64 {
```

2023-04-20 18:19 UTC, ilitteri commented on proving_system/stark/src/cairo_vm/instruction_flags.rs
Maybe having a `ToTraceRepresentation` or `TraceRepresentation` trait could be a good idea for the registers to implement, what do you think @pablodeymo @Oppen?

2023-04-20 20:37 UTC, entropidelic commented on proving_system/stark/src/air/trace.rs
> +        // dbg!(&n_rows);
removed ✅

2023-04-21 14:25 UTC, MauroToscano requested changes

2023-04-21 14:25 UTC, MauroToscano commented on proving_system/stark/src/cairo_vm/cairo_mem.rs
> +    }
It's not clear what a get function without description does. It could be renamed or at least some documentation could be added

2023-04-21 14:25 UTC, MauroToscano commented on proving_system/stark/src/cairo_vm/instruction_offsets.rs
> +fn to_unbiased_representation<F: IsField>(n: i32) -> FieldElement<F> {
It's not clear what an unbiased representation is, we could add documentation to this function, maybe the same for trace representation

2023-04-24 17:33 UTC, pablodeymo approved these changes
LGTM

2023-04-24 21:10 UTC, MauroToscano approved these changes

2023-04-24 21:16 UTC, merged