Fix FieldElement benchmarks
lambdaclass/lambdaworks pull request #511
Opened 2023-07-17 16:13 UTC by gabrielbosio

2023-07-18 16:15 UTC, Oppen approved these changes

2023-07-20 14:30 UTC, MauroToscano requested changes

2023-07-21 14:44 UTC, schouhy approved these changes

2023-07-21 14:45 UTC, ajgara approved these changes

2023-07-21 14:46 UTC, schouhy commented on benches/benches/utils.rs
> +        lambdaworks_vec.push(a);
It [does](https://github.com/arkworks-rs/algebra/blob/e0688b0ccc8d5d720bebaae0d52ef972ecf95e77/ff/src/fields/models/fp/montgomery_backend.rs#L372) (I if get what you mean).

2023-07-31 14:18 UTC, MauroToscano approved these changes

2023-07-31 14:27 UTC, merged