Stark: Remove degree adjustment from composition poly
lambdaclass/lambdaworks pull request #563
Opened 2023-09-19 20:48 UTC by schouhy

# TITLE

## Description

Description of the pull request changes and motivation.

## Type of change

Please delete options that are not relevant.

- [ ] New feature
- [ ] Bug fix
- [ ] Optimization

## Checklist
- [ ] Linked to Github Issue
- [ ] Unit tests added
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] This change is an Optimization
  - [ ] Benchmarks added/run

2023-09-20 16:04 UTC, ajgara approved these changes

2023-09-20 16:04 UTC, MauroToscano approved these changes

2023-09-20 16:55 UTC, MauroToscano requested changes
We should we update documentation @schouhy

2023-09-20 19:30 UTC, diegokingston approved these changes

2023-09-21 15:34 UTC, MauroToscano approved these changes

2023-09-21 15:53 UTC, merged