(feature): Bn254 Curve Implementation
lambdaclass/lambdaworks pull request #633
Opened 2023-10-27 01:20 UTC by protocolwhisper

# Bn254 Curve
- [x] Add the finite field used by the curve, using MontgomeryBackend
- [x] Add the curve
## Description

This partially close  https://github.com/lambdaclass/lambdaworks/issues/548

## Type of change

Please delete options that are not relevant.

- [x] New feature
## Checklist
- [x] Linked to Github Issue
- [x] Unit test added

2023-10-27 17:35 UTC, MauroToscano requested changes

2023-10-27 17:35 UTC, MauroToscano commented on math/src/elliptic_curve/short_weierstrass/curves/bn_254/curve.rs
> +            // I don't believe in this ut i gotta represent this in the other file
What's this comment ?

2023-10-27 17:35 UTC, MauroToscano commented on math/.vscode/settings.json
> +}
This file shouldn't be pushed

2023-10-29 00:46 UTC, protocolwhisper commented on math/.vscode/settings.json
> +}
My bad

2023-11-01 05:47 UTC, protocolwhisper commented
@MauroToscano I'm closing this PR cause this is being solved in this team PR: https://github.com/lambdaclass/lambdaworks/pull/646

2023-11-01 05:47 UTC, closed without merging