add new command to prove traces
lambdaclass/lambdaworks pull request #634
Opened 2023-10-27 02:02 UTC by mb-dci

+ prove-traces command added

# TITLE

## Description

Description of the pull request changes and motivation.

## Type of change

Please delete options that are not relevant.

- [ ] New feature
- [ ] Bug fix
- [ ] Optimization

## Checklist
- [ ] Linked to Github Issue
- [ ] Unit tests added
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] This change is an Optimization
  - [ ] Benchmarks added/run

2023-11-05 06:48 UTC, aniketpr01 commented
Current implementation has no builtin support, and range_check output is set to None.
We have only added one unit test of fibonacci_5 program as of now, if suggested, then will add for other programs as well. It may require to modify docker files to run with cairo-run entrypoint so that it will be able to generate the trace files when executed during make test, as in the current implementation we have just uploaded the trace files for fibonacci_5 program.

2023-11-06 17:28 UTC, MauroToscano approved these changes

2023-11-06 17:28 UTC, MauroToscano commented
Looking good

2023-11-06 17:55 UTC, MauroToscano commented
It would be cool to add this to the readme

2023-11-06 17:56 UTC, MauroToscano requested changes
Add to the readme the new command and how to use it with cairo-run

2023-11-06 20:48 UTC, entropidelic commented on provers/cairo/src/commands.rs
> +    ProveTrace(ProveTraceArgs),
Let's make a little change of names; I think it is more accurate if the `Prove` command is renamed to something like "RunAndProve" (the command description should be changed too), and the new command you implemented should be the one named `Prove`.
This reflects better the intent of both commands IMO

2023-11-06 20:51 UTC, entropidelic commented on provers/cairo/src/main.rs
> +            }
I think this check isn't really necessary, lets be more flexible on the files format. It really doesn't matter what the file extension is

2023-11-07 13:49 UTC, entropidelic approved these changes

2023-11-07 13:50 UTC, entropidelic commented
great work 🎉

2023-11-07 14:06 UTC, diegokingston approved these changes

2023-11-07 14:25 UTC, MauroToscano approved these changes

2023-11-07 14:35 UTC, merged