Implemented `std::iter::Sum` for `FieldElement`
lambdaclass/lambdaworks pull request #65
Opened 2023-02-14 15:31 UTC by AleksanderMisztal

2023-02-14 16:38 UTC, ilitteri commented on math/src/field/element.rs
> +        iter.fold(Self::zero(), |a, b| a + b)
Could we change the parameters name to `addend` and `augend` like this?
```suggestion
        iter.fold(Self::zero(), |augend, addend| augend + addend)
```

2023-02-14 16:39 UTC, ilitteri requested changes
The PR looks good! Just one minor change and we can merge!

2023-02-14 17:00 UTC, ilitteri approved these changes
LGTM

2023-02-14 17:01 UTC, AleksanderMisztal commented
Btw I have some spare time over the next few days, I could tackle something bigger. What's the best way to message you to discuss?

2023-02-14 17:19 UTC, ilitteri commented
> Btw I have some spare time over the next few days, I could tackle something bigger. What's the best way to message you to discuss?

First of all thanks for addressing the issue.

I think it'd be awesome if you tackle something bigger.

Regarding your question, I'll @unbalancedparentheses and @MauroToscano answer it.

2023-02-14 17:20 UTC, jrchatruc approved these changes

2023-02-15 01:09 UTC, unbalancedparentheses commented
Hi! The best way is that you join the telegram and we talk over there. You can find the telegram group in the readme!

2023-02-15 09:11 UTC, AleksanderMisztal commented
Thanks! But looks like that link is broken 👀

2023-02-17 20:05 UTC, ilitteri commented
> Thanks! But looks like that link is broken 👀

Fixed!

2023-02-17 20:05 UTC, ilitteri commented
Could you merge from `main` so we can run the CI?

2023-02-22 14:04 UTC, ilitteri commented
Sorry for the dealy, just one more detail. Could we add a test for this?

2023-02-24 15:23 UTC, MauroToscano commented
There is a small conflict, if it's fix we can merge it

2023-03-06 16:23 UTC, MauroToscano approved these changes

2023-03-06 16:26 UTC, merged