feat(math): Add to_hex(&self) -> String to FieldElement of a IsPrimeF…
lambdaclass/lambdaworks pull request #735
Opened 2023-12-28 21:06 UTC by emirsoyturk

# Add to_hex(&self) -> String to FieldElement of a IsPrimeField

## Description
This is PR for #104
Add to_hex(&self) -> String function to FieldElement and implement it where needed

This function should create an hexstring representing the number in FieldElement. It should abstract the user from the internal representation, so if the number is in Montgomery form, it should convert it back to the original form before returning the element.

## Type of change
- [x] New feature

## Checklist
- [x] Linked to Github Issue
- [x] Unit tests added
- [x] This change requires new documentation.
  - [x] Documentation has been added/updated.

2023-12-28 21:09 UTC, MauroToscano approved these changes, later dismissed

2024-01-02 20:50 UTC, MauroToscano approved these changes

2024-01-02 20:52 UTC, MauroToscano approved these changes

2024-01-02 20:53 UTC, diegokingston approved these changes, later dismissed

2024-01-02 20:59 UTC, MauroToscano requested changes

2024-01-02 20:59 UTC, MauroToscano commented on math/src/field/traits.rs
> +
It's missing the documentation on how this function should behave. It should have three bars /// and at least say what it does and the format of the output

2024-01-02 20:59 UTC, MauroToscano commented on math/src/field/element.rs
> +    // Creates a hexstring from a `FieldElement` without `0x`.
Use three /// so it documents

2024-01-02 21:02 UTC, entropidelic submitted a review, later dismissed

2024-01-02 21:04 UTC, entropidelic commented
lgtm, once @MauroToscano's changes are addressed this will be merged. Thank you @emirsoyturk 🎉

2024-01-02 21:11 UTC, MauroToscano approved these changes

2024-01-02 21:12 UTC, entropidelic approved these changes

2024-01-02 21:13 UTC, MauroToscano approved these changes

2024-01-02 21:18 UTC, merged