Fix UnsignedInteger test module
lambdaclass/lambdaworks pull request #78
Opened 2023-02-15 15:55 UTC by GianfrancoBazzani

# Fix UnsignedInteger test module

## Description

Fixed crate imports as https://github.com/lambdaclass/lambdaworks/pull/75 for both U384 and U256 types.
Added Byte conversion test for U256 type.

## Type of change

## Checklist

- [x] Unit tests added.

2023-02-15 15:58 UTC, ilitteri commented on math/src/unsigned_integer/element.rs
> +    fn from_bytes_le_works() {
A couple of new lines are missing here

2023-02-15 16:00 UTC, ilitteri requested changes
Looks good! With the merge conflicts solved and the new lines added we could merge.

2023-02-18 18:09 UTC, ilitteri approved these changes
LGTM, great work!

2023-02-18 21:14 UTC, MauroToscano commented
Looks good! Before merging we should check the CI is working. Can you merge with main ?

2023-02-22 12:42 UTC, jrchatruc approved these changes

2023-02-23 15:45 UTC, ilitteri requested changes
Could you merge with main so we could run the CI?

2023-02-23 15:57 UTC, ilitteri approved these changes

2023-02-23 15:58 UTC, MauroToscano approved these changes

2023-02-23 15:58 UTC, merged