WIP Add benchmark for fields
lambdaclass/lambdaworks pull request #80
Opened 2023-02-15 17:10 UTC by AminArria

2023-02-15 17:28 UTC, AminArria commented on math/Cargo.toml
> +criterion = "0.4"
Move to `dev-dependencies`

2023-02-15 20:39 UTC, ilitteri approved these changes

2023-02-16 15:14 UTC, MauroToscano commented
There should be a README, either in the main one or in the module, that says how to run the benchmarks.

 A make command to run all benches may be useful too.

2023-02-16 15:15 UTC, MauroToscano requested changes
Add documentation on how to run the benches. Add a command in the makefile to run all benches, and write in the main README how to run all benches or some of them.

2023-02-16 19:09 UTC, MauroToscano approved these changes

2023-02-16 19:10 UTC, merged