feat(ecc): Add Grumpkin curve + refactor fuzzer
lambdaclass/lambdaworks pull request #811
Opened 2024-02-23 03:24 UTC by PatStiles

# Add Grumpkin Curve

## Description

This pr adds an implementation of the grumpkin ecc which is a cycle curve over BN254 and used within the Aztec network. Additionally it performs a minor refactor for fuzzer module.

## Type of change

Please delete options that are not relevant.

- [x] New feature

2024-02-28 19:12 UTC, diegokingston approved these changes

2024-02-29 14:50 UTC, MauroToscano requested changes
It needs some test cases generated with Sage or another library

2024-02-29 18:40 UTC, PatStiles commented
Does this not qualify? https://github.com/lambdaclass/lambdaworks/pull/811/files#diff-cd24214c4896039a9c9dd13475bcddf6733717c300aa4f42533eb713b25a150dR102 Or do I need to add annotations for each specific test case?

2024-03-06 21:23 UTC, MauroToscano approved these changes

2024-03-06 21:43 UTC, merged