A task implementation from #830
lambdaclass/lambdaworks pull request #838
Opened 2024-03-07 18:50 UTC by skaunov

# TITLE

## Description

See #830

## Type of change

- [ ] New feature

## Checklist
- [x ] Linked to Github Issue
- [ ] Unit tests added
- [x] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] This change is an Optimization
  - [ ] Benchmarks added/run

2024-03-12 18:12 UTC, MauroToscano commented
There are some conflicts here

2024-03-12 23:21 UTC, skaunov commented
It's more surprising not to have them while active developing.

PS 
this one in particular due to the renaming you closed earlier I guess
but I won't be surprised by new conflicts pop up before positive review

2024-03-20 18:53 UTC, MauroToscano requested changes
Tests need to be added. It's looking good

2024-03-20 18:53 UTC, MauroToscano commented on math/src/elliptic_curve/short_weierstrass/point/jacobian.rs
> +    }
We should make the other new in projectives work like this too, I think it's easier to use. It can be made in a followup

2024-03-20 20:21 UTC, skaunov commented
I was planning to adapt tests from projective, but found no actual, only for bytes conversions IIRC.

* What's an other fine source of a test vectors suite?
* Is it ok if projective lacks actual tests?

2024-03-21 16:55 UTC, MauroToscano commented
> I was planning to adapt tests from projective, but found no actual, only for bytes conversions IIRC.
> 
>     * What's an other fine source of a test vectors suite?
> 
>     * Is it ok if projective lacks actual tests?

We don't have the tests in the general coordinates, because by their own they don't anything without a curve. But you could add it to the tests of the bls 12 381 for example, and test jacobians for that specific curve.

2024-03-26 18:29 UTC, skaunov commented
I'm planning to use affine for `tests` which will be testing if the results here match `Projective` after both reduced to affine; plus cover the other added functions.

Thing is I have couple of things which will end in couple of weeks, after which I would be happy to finish this one. If anything is really demanding/depending on this I can prioritize this.

I has the feeling that this one became outstanding and urges for an action just in spite of tidiness. If it's the case maybe we have an appropriate label here, or should we convert it to be draft for a couple of weeks?

2024-04-01 18:18 UTC, skaunov commented
I feel it was a mistake from to re-request review from Mauro... Sorry. =(

2024-04-08 10:22 UTC, MauroToscano commented
We are not in a hurry to finish it. We can wait. If for some reason you will abandon it, then do tell please.

2024-04-08 11:59 UTC, skaunov commented
Of course I would. But this one is finished with the last commit. I 
notified Irfan via Tg that it's ready for the final review and 
squashing&merging.

On Mon, Apr 8 2024 at 03:22:55 AM -0700, Mauro Toscano 
***@***.***> wrote:
> We are not in a hurry to finish it. We can wait. If for some reason 
> you will abandon it, then do tell please.
> 
> —
> Reply to this email directly, view it on GitHub 
> <https://github.com/lambdaclass/lambdaworks/pull/838#issuecomment-2042385689>, 
> or unsubscribe 
> <https://github.com/notifications/unsubscribe-auth/APXLOT6LFBU3ZMVRBSLGADTY4JVX7AVCNFSM6AAAAABELRF6ISVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDANBSGM4DKNRYHE>.
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>
>

2024-10-01 14:08 UTC, diegokingston commented
This functionality has already been added

2024-10-01 14:08 UTC, closed without merging