Improving docs
lambdaclass/lambdaworks pull request #901
Opened 2024-08-30 21:52 UTC by diegokingston

# TITLE

## Description

Description of the pull request changes and motivation.

## Type of change

Please delete options that are not relevant.

- [ ] New feature
- [ ] Bug fix
- [ ] Optimization

## Checklist
- [ ] Linked to Github Issue
- [ ] Unit tests added
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] This change is an Optimization
  - [ ] Benchmarks added/run

2024-09-05 15:36 UTC, igaray requested changes

2024-09-05 15:36 UTC, igaray commented on math/src/elliptic_curve/README.md
> +This allows us to reduce the amount of information we send to define a unique point on the curve. It suffices to specify $x$ and which of the two values (either $-$ or $+$) we shoudl take. This comes
shoudl -> should

2024-09-05 15:36 UTC, igaray commented on math/src/elliptic_curve/README.md
> +This allows us to reduce the amount of information we send to define a unique point on the curve. It suffices to specify $x$ and which of the two values (either $-$ or $+$) we shoudl take. This comes
which in generally a large collection of points 
-> 
which in general is a large collection of points

2024-09-05 15:36 UTC, igaray commented on math/src/elliptic_curve/README.md
> +In many curves, the base field contains some spare bits (as is the case of BLS12-381 or BN254, but not secp256k1), which allow us to codify the extra bit into the free bits of the element. Depending
allow -> allows

2024-09-05 16:06 UTC, diegokingston commented on math/src/elliptic_curve/README.md
> +In many curves, the base field contains some spare bits (as is the case of BLS12-381 or BN254, but not secp256k1), which allow us to codify the extra bit into the free bits of the element. Depending
Nice catch, just updated them

2024-09-06 18:04 UTC, igaray approved these changes

2024-09-09 15:34 UTC, merged